### ISSUE TITLE
Misuses of cryptographic APIs

### ISSUE THREAD

**Issue by mhp0rtal** [mob41/broadlink-java-api#22]
Hi
The following lines have cryptographic API misuses. <br> File name => src/main/java/com/github/mob41/blapi/pkt/auth/AES.java: Line number => 51: API name => Cipher:First parameter (with value "AES/CBC/NoPadding") should be any of AES/CBC/{Empty String, PKCS7Padding, PKCS5Padding, ISO10126Padding}<BR> File name => src/main/java/com/github/mob41/blapi/pkt/auth/AES.java: Line number => 52: API name => SecretKeySpec:<BR> File name => src/main/java/com/github/mob41/blapi/pkt/auth/AES.java: Line number => 57: API name => Cipher:First parameter (with value "AES/CBC/NoPadding") should be any of AES/CBC/{Empty String, PKCS7Padding, PKCS5Padding, ISO10126Padding}<BR> File name => src/main/java/com/github/mob41/blapi/pkt/auth/AES.java: Line number => 58: API name => SecretKeySpec:<BR> File name => src/main/java/com/github/mob41/blapi/pkt/auth/AES.java: Line number => 53: API name => Cipher:<BR> File name => src/main/java/com/github/mob41/blapi/pkt/auth/AES.java: Line number => 52: API name => IvParameterSpec:<BR> File name => src/main/java/com/github/mob41/blapi/pkt/auth/AES.java: Line number => 59: API name => Cipher:<BR> File name => src/main/java/com/github/mob41/blapi/pkt/auth/AES.java: Line number => 58: API name => SecretKeySpec:<BR> File name => src/main/java/com/github/mob41/blapi/pkt/auth/AES.java: Line number => 52: API name => SecretKeySpec:<BR> File name => src/main/java/com/github/mob41/blapi/pkt/auth/AES.java: Line number => 58: API name => IvParameterSpec:<BR> File name => src/main/java/com/github/mob41/blapi/pkt/auth/AES.java: Line number => 59: API name => Cipher:<BR> File name => src/main/java/com/github/mob41/blapi/pkt/auth/AES.java: Line number => 53: API name => Cipher:<BR>

**Comment by mob41** [comment]
What do you mean by “misuse”?

The padding must be no padding because the protocol requires. According to https://docs.oracle.com/javase/8/docs/technotes/guides/security/StandardNames.html , the standard name for no padding is <code>NoPadding</code> but not an empty string in Java SE 8. It would instead cause runtime error. Even for newer versions of Java, it’s the same.

Where does your machine-generated and hard-to-read stuff come from?

**Comment by bwssytems** [comment]
I've gotten a few of these as well. It's like they are trying to use github as an area they can say they researched for security and put it on their resume. Their review has nothing to do with the context the methods are being used in.

**Comment by mob41** [comment]
So, should I just ignore this one? I don’t see his/her account has any previous experience and contribution in GitHub.

**Comment by bwssytems** [comment]
Ignore it. The only ones that are real I have seen are reviews that come directly from github to your email.

**Comment by mob41** [comment]
Lol, these bots should be banned by GitHub. Without some experience in Java, people would be tricked by them.🧐

**Comment by lol768** [comment]
User has done this to some repos I'm involved with. Issues have been a waste of time on both occasions, one of them was because the automated tool or whatever it is had never seen an ECDSA signature before.

Would suggest reporting to GitHub, it's all noise.
